export const surprisePrompts = [
'An armchair in the shape of an avocado',
'A surrealist dream-like oil painting by Salvador Dalí of a cat playing checkers',
'Teddy bears shopping for groceries in Japan, ukiyo-e',
'An oil painting by Matisse of a humanoid robot playing chess',
'Panda mad scientist mixing sparkling chemicals, digital art',
"A macro 35mm photograph of two mice in Hawaii, they're each wearing tiny swimsuits and are carrying tiny surf boards, digital art",
'An astronaut lounging in a tropical resort in space, vaporwave',
'An oil painting portrait of a capybara wearing medieval royal robes and an ornate crown on a dark background',
'A stained glass window depicting a hamburger and french fries',
'A pencil and watercolor drawing of a bright city in the future with flying cars',
'A sunlit indoor lounge area with a pool with clear water and another pool with translucent pastel pink water, next to a big window, digital art',
'A fortune-telling shiba inu reading your fate in a giant hamburger, digital art',
'A sea otter with a pearl earring" by Johannes Vermeer',
'An oil pastel drawing of an annoyed cat in a spaceship',
'A painting of a fox in the style of Starry Night',
'A bowl of soup that looks like a monster, knitted out of wool',
'A plush toy robot sitting against a yellow wall',
'A synthwave style sunset above the reflecting water of the sea, digital art',
'Two futuristic towers with a skybridge covered in lush foliage, digital art',
'A 3D render of a rainbow colored hot air balloon flying above a reflective lake',
'A comic book cover of a superhero wearing headphones',
'A centered explosion of colorful powder on a black background',
'A photo of a Samoyed dog with its tongue out hugging a white Siamese cat',
'A photo of a white fur monster standing in a purple room',
"A photo of Michelangelo's sculpture of David wearing headphones djing",
'A Samurai riding a Horse on Mars, lomography.',
'A futuristic space station orbiting a distant alien planet, sci-fi illustration.',
'A whimsical candyland with giant lollipops and cotton candy clouds, digital painting.',
'An enchanted library filled with books that come to life, fantasy art.',
'A futuristic city skyline at sunset with neon lights and reflections, digital art.',
'A group of superheroes battling villains in a colorful cityscape, comic book style.',
'An underwater kingdom ruled by mermaids and sea creatures, fantasy art.',
'A magical portal leading to a parallel universe, digital painting.',
'A futuristic robot cafe where robots serve coffee to humans, sci-fi illustration.',
'A floating island in the sky with waterfalls and lush greenery, digital art.',
'A whimsical carousel with mythical creatures as rideable animals, fantasy art.',
'A cyberpunk street scene with hoverboards and holographic advertisements, digital art.',
'A futuristic laboratory where scientists conduct experiments on alien specimens, sci-fi illustration.',
'A futuristic race track where cars can fly and race in the sky, digital art.',
'A group of animals dressed in Victorian-era clothing attending a tea party, digital painting.',
'A time-traveling explorer discovering ancient ruins on an alien planet, sci-fi art.',
'A magical underwater garden with vibrant coral reefs and sea creatures, fantasy art.',
'A hidden wizard\'s tower nestled in a mystical forest, digital art.',
'A futuristic space colony with domed cities and advanced technology, sci-fi illustration.',
'A group of adventurers on a quest to find a lost treasure in a dangerous jungle, digital painting.',
'A futuristic city with floating islands and sky bridges, digital art.',
'A futuristic train station with high-speed trains and advanced technology, sci-fi art.',
'A group of fantasy creatures attending a masquerade ball, digital painting.',
'A steampunk robot with gears and cogs as its inner workings, digital art.',
'A magical marketplace with floating lanterns and enchanted goods, fantasy art.',
];