import React, { useState } from 'react';
import { useNavigate } from 'react-router-dom';

import { preview } from '../assets';
import { getRandomPrompt } from '../utils';
import { FormField, Loader } from '../components';

const CreateStory = () => {
  const navigate = useNavigate();
  const [form, setForm] = useState({
    name: '',
    prompt: '',
    photo: '',
  });

  const [generatingStory, setGeneratingStory] = useState(false);
  const [loading, setLoading] = useState(false)

  return (
    <section className="max-w-7xl mx-auto">
      <div>
        <h1 className="font-extrabold text-[#2223728] text-[32px]">Create</h1>
        <p className="mt-2 text-[#666e75] text-[16px] max-w[500px]">Create a story generated by OpenAI and DALL-E AI and share with the community</p>
      </div>

      <form className="mt-16 max-w-3xl">

      </form>
    </section>
  )
}

export default CreateStory